# Generated by Django 3.0.1 on 2019-12-30 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delete_book',
            field=models.BooleanField(default=False, verbose_name='delete status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='read_book',
            field=models.BooleanField(default=False, verbose_name='read status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_book',
            field=models.BooleanField(default=False, verbose_name='update status'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
